insert into DISCRIMINANT (shortcut, description) values ('BST', 'bocznica stacyjna');
insert into DISCRIMINANT (shortcut, description) values ('BSZ', 'bocznica szlakowa');
insert into DISCRIMINANT (shortcut, description) values ('L', 'ogólnodostępna bocznica szlakowa');
insert into DISCRIMINANT (shortcut, description) values ('LPO', 'ogólnodostępna bocznica szlakowa i przystanek osob');
insert into DISCRIMINANT (shortcut, description) values ('M', 'mijanka');
insert into DISCRIMINANT (shortcut, description) values ('ML', 'mijanka i ładownia');
insert into DISCRIMINANT (shortcut, description) values ('MLP', 'mijanka, ładownia i przystanek osobowy');
insert into DISCRIMINANT (shortcut, description) values ('MPO', 'mijanka i przystanek osobowy');
insert into DISCRIMINANT (shortcut, description) values ('ODGS', 'posterunek odgałęźny i przystanek służbowy');
insert into DISCRIMINANT (shortcut, description) values ('ODST', 'posterunek odstępowy');
insert into DISCRIMINANT (shortcut, description) values ('PBSP', 'posterunek bocznicowy szlakowy i przystanek osobow');
insert into DISCRIMINANT (shortcut, description) values ('PBST', 'posterunek bocznicowy stacyjny');
insert into DISCRIMINANT (shortcut, description) values ('PBSZ', 'posterunek bocznicowy szlakowy');
insert into DISCRIMINANT (shortcut, description) values ('PGL', 'posterunek odgałęźny i ładownia');
insert into DISCRIMINANT (shortcut, description) values ('PGLP', 'posterunek odgałęźny, przystanek osobowy i ładowni');
insert into DISCRIMINANT (shortcut, description) values ('PGR', 'przejście graniczne');
insert into DISCRIMINANT (shortcut, description) values ('PK', 'przystanek osobowy w kolejowej komunikacji autobus');
insert into DISCRIMINANT (shortcut, description) values ('PO', 'przystanek osobowy publiczny');
insert into DISCRIMINANT (shortcut, description) values ('PODG', 'posterunek odgałęźny');
insert into DISCRIMINANT (shortcut, description) values ('PODS', 'przystanek osobowy i posterunek odstępowy');
insert into DISCRIMINANT (shortcut, description) values ('POGM', 'posterunek odgałęźny i mijanka');
insert into DISCRIMINANT (shortcut, description) values ('POGP', 'przystanek osobowy i posterunek odgałęźny');
insert into DISCRIMINANT (shortcut, description) values ('POGT', 'przystanek osobowy i grupa torów towarowych');
insert into DISCRIMINANT (shortcut, description) values ('PP', 'punkt przeładunkowy');
insert into DISCRIMINANT (shortcut, description) values ('ST', 'stacja');
insert into DISCRIMINANT (shortcut, description) values ('STTH', 'stacja techniczna');