insert into RAILWAY_DEPARTMENT (NAME) values ('BIAŁYSTOK');
insert into RAILWAY_DEPARTMENT (NAME) values ('BYDGOSZCZ');
insert into RAILWAY_DEPARTMENT (NAME) values ('CZĘSTOCHOWA');
insert into RAILWAY_DEPARTMENT (NAME) values ('GDYNIA');
insert into RAILWAY_DEPARTMENT (NAME) values ('KIELCE');
insert into RAILWAY_DEPARTMENT (NAME) values ('KRAKÓW');
insert into RAILWAY_DEPARTMENT (NAME) values ('LUBLIN');
insert into RAILWAY_DEPARTMENT (NAME) values ('ŁÓDŹ');
insert into RAILWAY_DEPARTMENT (NAME) values ('NOWY SĄCZ');
insert into RAILWAY_DEPARTMENT (NAME) values ('OLSZTYN');
insert into RAILWAY_DEPARTMENT (NAME) values ('OPOLE');
insert into RAILWAY_DEPARTMENT (NAME) values ('OSTRÓW WIELKOPOLSKI');
insert into RAILWAY_DEPARTMENT (NAME) values ('POZNAŃ');
insert into RAILWAY_DEPARTMENT (NAME) values ('RZESZÓW');
insert into RAILWAY_DEPARTMENT (NAME) values ('SIEDLCE');
insert into RAILWAY_DEPARTMENT (NAME) values ('SKARŻYSKO-KAMIENNA');
insert into RAILWAY_DEPARTMENT (NAME) values ('SOSNOWIEC');
insert into RAILWAY_DEPARTMENT (NAME) values ('SZCZECIN');
insert into RAILWAY_DEPARTMENT (NAME) values ('TARNOWSKIE GÓRY');
insert into RAILWAY_DEPARTMENT (NAME) values ('WAŁBRZYCH');
insert into RAILWAY_DEPARTMENT (NAME) values ('WARSZAWA');
insert into RAILWAY_DEPARTMENT (NAME) values ('WROCŁAW');
insert into RAILWAY_DEPARTMENT (NAME) values ('ZIELONA GÓRA');